# Generated by Django 5.1.6 on 2025-02-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
